### ISSUE TITLE
Hi dear authors, I want the script of producing synthetic data, much grateful if you will release it

### ISSUE THREAD

**Issue by Serenade-J** [awasthiabhijeet/PIE#1]
Hi dear authors of PIE, I am a student from Peking University, learning NAR-GEC task now. This is a so excellent and impressive work. To reproduce the result you achieved, I want to know how many sentence pairs in the One-Billion-word corpus were used to pre-train the model. And I will be much grateful if you will release the script for producing synthetic data. My email is zjy0307@pku.edu.cn  Thank u so much.

**Comment by awasthiabhijeet** [comment]
Hi, we will be releasing it soon. Most likely by the start of next week.

**Comment by Serenade-J** [comment]
> Hi, we will be releasing it soon. Most likely by the start of next week.

Hi, will it be released recently?

**Comment by awasthiabhijeet** [comment]
Sorry for the delay!
Synthetic data and scripts used for creating it have now been released.

Thanks for appreciating our work! :)
