### ISSUE TITLE
Pretrained model bad correction performance?

### ISSUE THREAD

**Issue by raff7** [awasthiabhijeet/PIE#11]
Hi, I am testing out your model and i noticed that if i run your pretrained model on the conll_test.txt file you have it get very poor performances. the output is something of the sort:

```
Day I think I think I think remember I think I think I
Day What I think is here and I think and I
Day I think large refers every day large your every day chance every day of I think every daying every day large I think I am disease every day every day
```

which has no resemblance with the input. do you maybe know what might be going on? I am just running multi_round_infer.sh. the only flags i have changed are "use_tpu" to false (cause i dont have a tpu and im runnign on gpu).

**Comment by awasthiabhijeet** [comment]
Hi!
It seems that the checkpoint is not loaded. What was the original input sentence in case?

Are you using the scrips provided [here](https://github.com/awasthiabhijeet/PIE/tree/master/PIE_ckpt) ?

**Comment by raff7** [comment]
oh i see, i was running the script in "example_scripts" instad of the one in the checkpoint folder. thanks for your quick help.
