### ISSUE TITLE
Inference using own sentences

### ISSUE THREAD

**Issue by tuhinjubcse** [awasthiabhijeet/PIE#14]
Hi
Authors

Could you please tell me how to infer on my own tests set of grammatically incorrect sentences ?

**Comment by awasthiabhijeet** [comment]
Hi Tuhin,
Thanks for your interest in our work.

You simply need to change the path of input_file in [this](https://github.com/awasthiabhijeet/PIE/blob/master/PIE_ckpt/multi_round_infer.sh) script and point it to your own test set. 

Similar issues which have been resolved previously:

- https://github.com/awasthiabhijeet/PIE/issues/5

- https://github.com/awasthiabhijeet/PIE/issues/11

**Comment by awasthiabhijeet** [comment]
Hi @tuhinjubcse ,
please let me know, if you the above reply was helpful to you so that I can close this issue.

Thanks.
