### ISSUE TITLE
What impact does it have on the overall time with this variable set.

### ISSUE THREAD

**Issue by pidugusundeep** [awasthiabhijeet/PIE#16]
https://github.com/awasthiabhijeet/PIE/blob/2975a6cb3d3ecccddee21d3a0fc094155550dddb/apply_opcode.py#L30

**Comment by awasthiabhijeet** [comment]
This was implemented to speed up applying opcodes if the test set is very very large.
The results in the paper are without using this feature. Also, time for applying opcodes is negligible in comparison to inference time in the PIE model.  
I did not spend enough time in testing this feature, as it was not used much. Hence, it is currently set to False.
