### ISSUE TITLE
what's the diff between PIE and LaserTagger ?

### ISSUE THREAD

**Issue by Lingogo** [awasthiabhijeet/PIE#19]

**Comment by awasthiabhijeet** [comment]
Hi, 
I think PIE and LaserTagger are conceptually very much similar ideas. Coincidentally, both the papers appeared in EMNLP 2019.

In my personal opinion, here are a few key differences

1. PIE is fully non-autoregressive.  We do not require an auto-regressive layer to output a sequence of edit tokens. Token-level edits are predicted at each position, in parallel. Thus I expect PIE to be faster. 
2. PIE was primarily developed for Grammatical Error Correction (GEC) and later extended to OCR-denoising and Spell-Correction. Apart from GEC, laser-tagger considers tasks like text-simplification and summarization.
3. I think our GEC numbers are much stronger and easier to reproduce exactly.
