### ISSUE TITLE
Found  Garbled in the Synthetic Dataset

### ISSUE THREAD

**Issue by KYRIEZX** [awasthiabhijeet/PIE#26]
![image](https://user-images.githubusercontent.com/56826566/99207777-c9264300-27f9-11eb-92b1-1339a09831d4.png)
Just like this. Is it still available to be trained?

**Comment by awasthiabhijeet** [comment]
Hi @KYRIEZX 
Sorry for replying so late.

Could you please confirm if you were able to download the synthetic dataset?
